export const pricingDetails = [
  {
    id: 1,
    planName: "Elite",
    planAmount: "$25000/",
    planDetails: [
      "Trading leverage 1:1000",
      "Ultra-low spread / Raw spread",
      "$1.5 per lot",
      "Dedicated Account Manager",
      "Exclusive daily market reports",
      "Custom trading conditions",
      "Trade: Forex, Commodity, Crypto, Indices, Stocks",
      "Special promotions & rewards",
    ],
  },
  {
    id: 2,
    planName: "Pro",
    planAmount: "$3000/",
    planDetails: [
      "Minimum Deposit $3000",
      "Trading leverage 1:300",
      "Low Spread",
      "2.5 Per lot",
      "Instant Withdraw",
      "Trade: Forex & Commodity",
      "24/7 Support",
    ],
  },
  {
    id: 3,
    planName: "Classic",
    planAmount: "$500/",
    planDetails: [
      "Minimum Deposit $500",
      "Trading leverage 1:200",
      "Floating Spread",
      "Zero commissions",
      "Instant Withdraw",
      "24/7 Support",
    ],
  },
  {
    id: 4,
    planName: "Standard",
    planAmount: "$200/",
    planDetails: [
      "Minimum Deposit $200",
      "Trading leverage 1:100",
      "Fixed spread",
      "Zero commissions",
      "Instant Withdraw",
      "24/7 Support",
    ],
  },
  {
    id: 5,
    planName: "VIP",
    planAmount: "$10000/",
    planDetails: [
      "Minimum Deposit $10000",
      "Trading leverage 1:500",
      "Very low spread",
      "3 Per lot",
      "24/7 Support",
      "Special Promotions",
      "Trade: Forex, Commodity, Crypto, Indices",
    ],
  },
];
